### ISSUE TITLE
WebSocket should be on by default

### ISSUE THREAD

**Issue by warpech** [PuppetJs/puppet-client#2]
For some reason, WebSocket stopped being on by default in current versions of puppet-client

**Comment by miyconst** [comment]
It looke like the setting is saved in `window.localStorage`, so it remembers it's state after page refresh and SC reinstallation.

**Comment by warpech** [comment]
True... I did not realize that because it persists between apps (when you set it in Launcher and then stop launcher and start some standalone app - it is still remembered).

It is ok, but could you rename the localStorage key? I propose to change it from `launcher-puppet-js-useWebSocket`  to `starcounter-debug-aid-puppet-js-useWebSocket`

**Comment by miyconst** [comment]
Done.
