### ISSUE TITLE
bindTo should be executed after obj value set

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/puppet-client#4]
In shimmed browsers like IE and FF it happens that `bindTo` called before connection established. This results in empty page bug. The event flow looks like this:

1. Create `puppet-client`.
2. Begin establishing connection.
3. Set `element.model` to `puppet-client.obj`.
4. Finish establishing connection.
5. Update `puppet-client.obj`.
6. Start listening to changes.
7. `element.model` changed, but Polymer never notified about it.

**Comment by miyconst** [comment]
Was just discovered by @andwah that this also happens in Chrome if establishing connection takes quite some time.

**Comment by miyconst** [comment]
I have fixed the issue. @tomalec take a look please.

**Comment by tomalec** [comment]
LGTM.
It seems to be related to the changes made by @warpech in PuppetJs, does it work fine with [custom-jsonpatch branch](https://github.com/PuppetJs/PuppetJs/tree/custom-jsonpatch) ?

**Comment by miyconst** [comment]
Not tested with the branch.

Should I release the `puppet-client` with this fix then?

**Comment by tomalec** [comment]
Please test it with this branch first. We are going to merge it with master soon.

**Comment by miyconst** [comment]
Tested with SysUpgrade app. Works good.

Released as [1.0.5](https://github.com/PuppetJs/puppet-client/releases/tag/1.0.5). Starcounter nightly /sys/ folder updated.
