### ISSUE TITLE
Unsupported patch operation in patch.

### ISSUE THREAD

**Issue by SenerDemiral** [PuppetJs/puppet-client#5]
I have long button element.
```
<button class="heading" value="{{item.Toggle$::click}}" onclick="++this.value">
        {{item.Ad}}
        <span style="float:right">{{item.Tarih}}</span>
</button>
```
If clicked on item.Ad all expected,
but clicked on span
Connection error. See console for details. Reload page

Console:
puppet-client.html: 371
Unsupported patch operation in patch.

Any advice?

**Comment by Mackiovello** [comment]
It's the same issue as [this](https://github.com/Polymer/polymer/issues/2497). 

The trick is to do something like this:
```
<button class="heading" value="{{item.Toggle$::click}}" on-click="onToggleClick">
        {{item.Ad}}
        <span style="float:right">{{item.Tarih}}</span>
</button>
``` 
And then add:
```
    <script>
        (function () {
            var script = document._currentScript || document.currentScript;
            var template = script.previousElementSibling;

            template.onToggleClick = function (event) {
                  template.set("item.Toggle$", parseInt(template.get(item.Toggle$), 10) + 1);
            }
        })();
    </script>
```

Note the change from `onclick` to `on-click`

**Comment by SenerDemiral** [comment]
Thanks,
Waiting Polymer to fix it.

**Comment by warpech** [comment]
@Mackiovello thanks for answering, great answer!

**Comment by tomalec** [comment]
> Waiting Polymer to fix it.

Fixed in Polymer by us. Sorry, that it took that long.
https://github.com/Polymer/polymer/pull/5309

**Comment by SenerDemiral** [comment]
Finally! 
Thanks.
